### ISSUE TITLE
Generated random numbers in JS

### ISSUE THREAD

**Issue by MadhuSaini22** [tanyagupta0201/Hacktoberfest-2022#145]
@tanyagupta0201 Please assign this task to me with Hacktoberfest label

**Comment by tanyagupta0201** [comment]
assigned

**Comment by adnansam110** [comment]
Can you assign this to me as well please @tanyagupta0201 ?

**Comment by tanyagupta0201** [comment]
> Can you assign this to me as well please @tanyagupta0201 ?

You may do it in a language other than JS as it is already assigned.
