### ISSUE TITLE
Cycle detection in undirected graph [Graph][C++] 

### ISSUE THREAD

**Issue by Shiyadh123** [tanyagupta0201/Hacktoberfest-2022#55]
I would like to add the program to detect cycle if present in an undirected graph.
Please assign this task to me @tanyagupta0201

**Comment by tanyagupta0201** [comment]
Assigned

**Comment by BishtAmi** [comment]
I want to add the program to detect cycle in a undirected graph . plz assign this task to me @tanyagupta0201

**Comment by tanyagupta0201** [comment]
> I want to add the program to detect cycle in a undirected graph . plz assign this task to me @tanyagupta0201

Hey, this task is already assigned in C++. If you want this code you can do it in any other language other than C++.

**Comment by BishtAmi** [comment]
can i do this in C ?

**Comment by tanyagupta0201** [comment]
> can i do this in C ?

yes

**Comment by Shiyadh123** [comment]
C++ version has been added in PR #58 .
Please check and Merge @tanyagupta0201
