### ISSUE TITLE
Binary search code in C++

### ISSUE THREAD

**Issue by RajatRathore123-github** [tanyagupta0201/Hacktoberfest-2022#67]
hey i want to contribute binary search code in C++ can  you assign me this

**Comment by tanyagupta0201** [comment]
This problem is already done in C++ in PR #28.  You can do it any other language or do some other problem.

**Comment by BishtAmi** [comment]
i want to contribute this in C . plz assign this to me..

**Comment by tanyagupta0201** [comment]
> i want to contribute this in C . plz assign this to me..

assigned

**Comment by RajatRathore123-github** [comment]
can i contribute gcd of two number using euclid geomtry code in c++ .plz assign me

**Comment by tanyagupta0201** [comment]
> can i contribute gcd of two number using euclid geomtry code in c++ .plz assign me

Assigned

**Comment by BishtAmi** [comment]
> this
Created pull request #77 
kindly verify and merge

**Comment by RajatRathore123-github** [comment]
made a pr #78 
please verify it

**Comment by tanyagupta0201** [comment]
> made a pr #78 please verify it

Merged
